class Country {}

Country.flag_sssr = "images/flags-normal/sssr.gif";
Country.flag_sssr_m = "images/flags-mini/sssr.gif";
Country.flag_yu = "images/flags-normal/yu.jpg";
Country.flag_yu_m = "images/flags-mini/yu.jpg";
Country.flag_belarus = "images/flags-normal/by.png";
Country.flag_belarus_m = "images/flags-mini/by.png";
Country.flag_cyprus = "images/flags-normal/cy.png";
Country.flag_cyprus_m = "images/flags-mini/cy.png";
Country.flag_spain = "images/flags-normal/es.png";
Country.flag_spain_m = "images/flags-mini/es.png";
Country.flag_bulgaria = "images/flags-normal/bg.png";
Country.flag_bulgaria_m = "images/flags-mini/bg.png";
Country.flag_portugal = "images/flags-normal/pt.png";
Country.flag_portugal_m = "images/flags-mini/pt.png";
Country.flag_iceland = "images/flags-normal/is.png";
Country.flag_iceland_m = "images/flags-mini/is.png";
Country.flag_kazakhstan = "images/flags-normal/kz.png";
Country.flag_kazakhstan_m = "images/flags-mini/kz.png";
Country.flag_georgia = "images/flags-normal/ge.png";
Country.flag_georgia_m = "images/flags-mini/ge.png";
Country.flag_morocco = "images/flags-normal/ma.png";
Country.flag_morocco_m = "images/flags-mini/ma.png";
Country.flag_south_korea = "images/flags-normal/kr.png";
Country.flag_south_korea_m = "images/flags-mini/kr.png";
Country.flag_chine = "images/flags-normal/cn.png";
Country.flag_chine_m = "images/flags-mini/cn.png";
Country.flag_usa = "images/flags-normal/us.png";
Country.flag_usa_m = "images/flags-mini/us.png";
Country.flag_hungary = "images/flags-normal/hu.png";
Country.flag_hungary_m = "images/flags-mini/hu.png";
Country.flag_ukraine = "images/flags-normal/ua.png";
Country.flag_ukraine_m = "images/flags-mini/ua.png";
Country.flag_canada = "images/flags-normal/ca.png";
Country.flag_canada_m = "images/flags-mini/ca.png";
Country.flag_indonezia = "images/flags-normal/id.png";
Country.flag_indonezia_m = "images/flags-mini/id.png";
Country.flag_japan = "images/flags-normal/jp.png";
Country.flag_japan_m = "images/flags-mini/jp.png";
Country.flag_france = "images/flags-normal/fr.png";
Country.flag_france_m = "images/flags-mini/fr.png";
Country.flag_new_zeland = "images/flags-normal/nz.png";
Country.flag_new_zeland_m = "images/flags-mini/nz.png";
Country.flag_vietnam = "images/flags-normal/vn.png";
Country.flag_vietnam_m = "images/flags-mini/vn.png";
Country.flag_netherlands = "images/flags-normal/nl.png";
Country.flag_netherlands_m = "images/flags-mini/nl.png";
Country.flag_poland = "images/flags-normal/pl.png";
Country.flag_poland_m = "images/flags-mini/pl.png";
Country.flag_czechia = "images/flags-normal/cz.png";
Country.flag_czechia_m = "images/flags-mini/cz.png";
Country.flag_izrail = "images/flags-normal/il.png";
Country.flag_izrail_m = "images/flags-mini/il.png";
Country.flag_thailand = "images/flags-normal/th.png";
Country.flag_thailand_m = "images/flags-mini/th.png";
Country.flag_croatia = "images/flags-normal/hr.png";
Country.flag_croatia_m = "images/flags-mini/hr.png";
Country.flag_italy = "images/flags-normal/it.png";
Country.flag_italy_m = "images/flags-mini/it.png";
Country.flag_russia = "images/flags-normal/ru.png";
Country.flag_russia_m = "images/flags-mini/ru.png";
Country.flag_germany = "images/flags-normal/de.png";
Country.flag_germany_m = "images/flags-mini/de.png";
Country.flag_australia = "images/flags-normal/au.png";
Country.flag_australia_m = "images/flags-mini/au.png";
Country.flag_belgium = "images/flags-normal/be.png";
Country.flag_belgium_m = "images/flags-mini/be.png";
Country.flag_england = "images/flags-normal/gb.png";
Country.flag_england_m = "images/flags-mini/gb.png";
Country.flag_finland = "images/flags-normal/fi.png";
Country.flag_finland_m = "images/flags-mini/fi.png";
Country.flag_slovenia = "images/flags-normal/si.png";
Country.flag_slovenia_m = "images/flags-mini/si.png";
Country.flag_chili = "images/flags-normal/cl.png";
Country.flag_chili_m = "images/flags-mini/cl.png";
Country.flag_serbia = "images/flags-normal/rs.png";
Country.flag_serbia_m = "images/flags-mini/rs.png";
Country.flag_argentina = "images/flags-normal/ar.png";
Country.flag_argentina_m = "images/flags-mini/ar.png";
Country.flag_slovakia = "images/flags-normal/sk.png";
Country.flag_slovakia_m = "images/flags-mini/sk.png";
Country.flag_litva = "images/flags-normal/lt.png";
Country.flag_litva_m = "images/flags-mini/lt.png";
Country.flag_ireland = "images/flags-normal/ie.png";
Country.flag_ireland_m = "images/flags-mini/ie.png";
Country.flag_malaizia = "images/flags-normal/my.png";
Country.flag_malaizia_m = "images/flags-mini/my.png";
Country.flag_ruminia = "images/flags-normal/ro.png";
Country.flag_ruminia_m = "images/flags-mini/ro.png";
Country.flag_dania = "images/flags-normal/dk.png";
Country.flag_dania_m = "images/flags-mini/dk.png";
Country.flag_brazil = "images/flags-normal/br.png";
Country.flag_brazil_m = "images/flags-mini/br.png";
Country.flag_norway = "images/flags-normal/no.png";
Country.flag_norway_m = "images/flags-mini/no.png";
Country.flag_sweden = "images/flags-normal/se.png";
Country.flag_sweden_m = "images/flags-mini/se.png";
Country.flag_columbia = "images/flags-normal/co.png";
Country.flag_columbia_m = "images/flags-mini/co.png";
Country.flag_mexico = "images/flags-normal/mx.png";
Country.flag_mexico_m = "images/flags-mini/mx.png";
Country.flag_nepal = "images/flags-normal/np.png";
Country.flag_nepal_m = "images/flags-mini/np.png";
Country.flag_swiz = "images/flags-normal/ch.png";
Country.flag_swiz_m = "images/flags-mini/ch.png";
Country.flag_south_africa = "images/flags-normal/za.png";
Country.flag_south_africa_m = "images/flags-mini/za.png";
Country.flag_austria = "images/flags-normal/at.png";
Country.flag_austria_m = "images/flags-mini/at.png";
Country.flag_gvatemala = "images/flags-normal/gt.png";
Country.flag_gvatemala_m = "images/flags-mini/gt.png";
Country.flag_turkie = "images/flags-normal/tr.png";
Country.flag_turkie_m = "images/flags-mini/tr.png";
Country.flag_mongolia = "images/flags-normal/mn.png";
Country.flag_mongolia_m = "images/flags-mini/mn.png";
Country.flag_filippini = "images/flags-normal/ph.png";
Country.flag_filippini_m = "images/flags-mini/ph.png";
Country.flag_azerb = "images/flags-normal/az.png";
Country.flag_azerb_m = "images/flags-mini/az.png";
Country.flag_india = "images/flags-normal/in.png";
Country.flag_india_m = "images/flags-mini/in.png";
Country.flag_brunei = "images/flags-normal/bn.png";
Country.flag_brunei_m = "images/flags-mini/bn.png";
Country.flag_honhong = "images/flags-normal/hh.png";
Country.flag_honhong_m = "images/flags-mini/hh.png";
Country.flag_taiwan = "images/flags-normal/tw.png";
Country.flag_taiwan_m = "images/flags-mini/tw.png";
Country.flag_makao = "images/flags-normal/makao.png";
Country.flag_makao_m = "images/flags-mini/makao.png";
Country.flag_singapur = "images/flags-normal/sg.png";
Country.flag_singapur_m = "images/flags-mini/sg.png";
Country.flag_peru = "images/flags-normal/pe.png";
Country.flag_peru_m = "images/flags-mini/pe.png";
Country.flag_venezuela = "images/flags-normal/ve.png";
Country.flag_venezuela_m = "images/flags-mini/ve.png";
Country.flag_ecuador = "images/flags-normal/ec.png";
Country.flag_ecuador_m = "images/flags-mini/ec.png";
Country.flag_costa_rica = "images/flags-normal/cr.png";
Country.flag_costa_rica_m = "images/flags-mini/cr.png";
Country.flag_lux = "images/flags-normal/lu.png";
Country.flag_lux_m = "images/flags-mini/lu.png";
Country.flag_panama = "images/flags-normal/pa.png";
Country.flag_panama_m = "images/flags-mini/pa.png";
Country.flag_north_kore = "images/flags-normal/kp.png";
Country.flag_north_kore_m = "images/flags-mini/kp.png";
Country.flag_greece = "images/flags-normal/gr.png";
Country.flag_greece_m = "images/flags-mini/gr.png";


Country.cf_map_m = new Map();
Country.cf_map_m.set("СССР", Country.flag_sssr_m);
Country.cf_map_m.set("Югославия", Country.flag_yu_m);
Country.cf_map_m.set("Беларусь", Country.flag_belarus_m);
Country.cf_map_m.set("Кипр", Country.flag_cyprus_m);
Country.cf_map_m.set("Испания", Country.flag_spain_m);
Country.cf_map_m.set("Болгария", Country.flag_bulgaria_m);
Country.cf_map_m.set("Португалия", Country.flag_portugal_m);
Country.cf_map_m.set("Исландия", Country.flag_iceland_m);
Country.cf_map_m.set("Казахстан", Country.flag_kazakhstan_m);
Country.cf_map_m.set("Грузия", Country.flag_georgia_m);
Country.cf_map_m.set("Марокко", Country.flag_morocco_m);
Country.cf_map_m.set("Китай", Country.flag_chine_m);
Country.cf_map_m.set("Южная Корея", Country.flag_south_korea_m);
Country.cf_map_m.set("США", Country.flag_usa_m);
Country.cf_map_m.set("Венгрия", Country.flag_hungary_m);
Country.cf_map_m.set("Украина", Country.flag_ukraine_m);
Country.cf_map_m.set("Канада", Country.flag_canada_m);
Country.cf_map_m.set("Индонезия", Country.flag_indonezia_m);
Country.cf_map_m.set("Япония", Country.flag_japan_m);
Country.cf_map_m.set("Франция", Country.flag_france_m);
Country.cf_map_m.set("Новая Зеландия", Country.flag_new_zeland_m);
Country.cf_map_m.set("Голландия", Country.flag_netherlands_m);
Country.cf_map_m.set("Нидерланды", Country.flag_netherlands_m);
Country.cf_map_m.set("Вьетнам", Country.flag_vietnam_m);
Country.cf_map_m.set("Польша", Country.flag_poland_m);
Country.cf_map_m.set("Чехия", Country.flag_czechia_m);
Country.cf_map_m.set("Чехословакия", Country.flag_czechia_m);
Country.cf_map_m.set("Израиль", Country.flag_izrail_m);
Country.cf_map_m.set("Таиланд", Country.flag_thailand_m);
Country.cf_map_m.set("Хорватия", Country.flag_croatia_m);
Country.cf_map_m.set("Италия", Country.flag_italy_m);
Country.cf_map_m.set("Россия", Country.flag_russia_m);
Country.cf_map_m.set("Германия", Country.flag_germany_m);
Country.cf_map_m.set("Австралия", Country.flag_australia_m);
Country.cf_map_m.set("Бельгия", Country.flag_belgium_m);
Country.cf_map_m.set("Англия", Country.flag_england_m);
Country.cf_map_m.set("Великобритания", Country.flag_england_m);
Country.cf_map_m.set("Финляндия", Country.flag_finland_m);
Country.cf_map_m.set("Словения", Country.flag_slovenia_m);
Country.cf_map_m.set("Чили", Country.flag_chili_m);
Country.cf_map_m.set("Сербия", Country.flag_serbia_m);
Country.cf_map_m.set("Аргентина", Country.flag_argentina_m);
Country.cf_map_m.set("Словакия", Country.flag_slovakia_m);
Country.cf_map_m.set("Литва", Country.flag_litva_m);
Country.cf_map_m.set("Ирландия", Country.flag_ireland_m);
Country.cf_map_m.set("Малайзия", Country.flag_malaizia_m);
Country.cf_map_m.set("Румыния", Country.flag_ruminia_m);
Country.cf_map_m.set("Дания", Country.flag_dania_m);
Country.cf_map_m.set("Норвегия", Country.flag_norway_m);
Country.cf_map_m.set("Бразилия", Country.flag_brazil_m);
Country.cf_map_m.set("Швеция", Country.flag_sweden_m);
Country.cf_map_m.set("Колумбия", Country.flag_columbia_m);
Country.cf_map_m.set("Мексика", Country.flag_mexico_m);
Country.cf_map_m.set("Непал", Country.flag_nepal_m);
Country.cf_map_m.set("Швейцария", Country.flag_swiz_m);
Country.cf_map_m.set("Южная Африка", Country.flag_south_africa_m);
Country.cf_map_m.set("Австрия", Country.flag_austria_m);
Country.cf_map_m.set("Гватемала", Country.flag_gvatemala_m);
Country.cf_map_m.set("Турция", Country.flag_turkie_m);
Country.cf_map_m.set("Монголия", Country.flag_mongolia_m);
Country.cf_map_m.set("Азербайджан", Country.flag_azerb_m);
Country.cf_map_m.set("Филиппины", Country.flag_filippini_m);
Country.cf_map_m.set("Индия", Country.flag_india_m);
Country.cf_map_m.set("Бруней", Country.flag_brunei_m);
Country.cf_map_m.set("Гонконг", Country.flag_honhong_m);
Country.cf_map_m.set("Тайвань", Country.flag_taiwan_m);
Country.cf_map_m.set("Макао", Country.flag_makao_m);
Country.cf_map_m.set("Сингапур", Country.flag_singapur_m);
Country.cf_map_m.set("Эквадор", Country.flag_ecuador_m);
Country.cf_map_m.set("Венесуэла", Country.flag_venezuela_m);
Country.cf_map_m.set("Коста-Рика", Country.flag_costa_rica_m);
Country.cf_map_m.set("Северная Корея", Country.flag_north_kore_m);
Country.cf_map_m.set("Панама", Country.flag_panama_m);
Country.cf_map_m.set("Люксембург", Country.flag_lux_m);
Country.cf_map_m.set("Перу", Country.flag_peru_m);
Country.cf_map_m.set("Греция", Country.flag_greece_m);

Object.freeze(Country);