var matches_2018 = [];
var matches_2019 = [
    {
        'date': '08.10.2019',
        'match_number': 'match-belarus-cyprus-2019-10-08',
        'title': 'League D 2019/2020 1 тур',
        'flag1': 'images/flags-normal/by.png',
        'name1': 'Беларусь',
        'score1': '1',
        'player11': 'Супонев Александр Михайлович',
        'photo11': 'images/persons/sup_al.jpg',
        'score11': '0',
        'player12': 'Бусько Илья Владимирович',
        'photo12': 'images/persons/bus_il.jpg',
        'score12': '1',
        'player13': 'Герасютин Никита Эдуардович',
        'photo13': 'images/persons/ger_nik.jpg',
        'score13': '0',
        'player14': 'Корбут Сергей',
        'photo14': 'images/persons/kor_se.jpg',
        'score14': '0',
        'flag2': 'images/flags-normal/cy.png',
        'name2': 'Кипр',
        'score2': '3',
        'player21': 'Dimitris Regginos',
        'photo21': 'images/persons/ciprus/reg.jpg',
        'score21': '1',
        'player22': 'Dimitris Katsouris',
        'photo22': 'images/persons/ciprus/Kats.jpg',
        'score22': '0',
        'player23': 'Sotiris Ioannides',
        'photo23': 'images/persons/ciprus/Ioannides.jpg',
        'score23': '1',
        'player24': 'Phedias Christodoulides',
        'photo24': 'images/persons/ciprus/Christod.jpg',
        'score24': '1',
        'author': 'Герасютин Никита',
        'person_photo': 'images/persons/ger_nik.jpg',
        'news_ref': 'html/matches/2019_10_08_by_cyprus.html',
        'address': 'pandanet-igs.com',
        'www_ref': 'https://pandanet-igs.com/communities/euroteamchamps/rounds/607#3',
        'ref_name': 'Беларусь - Кипр',
        'place_css': 'images/places/panda.jpg',
        'video_ref': 'results/matches/belarus-ciprus/belarus-ciprus.mp4',
        'video_author': 'Динерштейн Александр Григорьевич',
        'author_css': 'pink',
        'author_ref': './html/pages/players_lib.html',
        'm1': 'results/matches/belarus-ciprus/1. Александр Михайлович(ч)-Dimitris Regginos.sgf',
        'm1_w': 'results/matches/belarus-ciprus/g1.sgf',
        'm1_name_b': 'Супонев Александр Михайлович',
        'm1_name_w': 'Dimitris Regginos',
        'm1_photo_b': 'images/persons/sup_al.jpg',
        'm1_photo_w': 'images/persons/ciprus/reg.jpg',
        'm1_score_b': '0',
        'm1_score_w': '1',
        'm1_res_col': '&#9675;',
        'm1_res_score': 'Сдача',
        'm1_flag_b': Country.flag_belarus_m,
        'm1_flag_w': Country.flag_cyprus_m,
        'm2': 'results/matches/belarus-ciprus/2. Бусько Илья(ч)-Dimitris Katsouris.sgf',
        'm2_w': 'results/matches/belarus-ciprus/g2.sgf',
        'm2_name_b': 'Бусько Илья Владимирович',
        'm2_name_w': 'Dimitris Katsouris',
        'm2_photo_b': 'images/persons/bus_il.jpg',
        'm2_photo_w': 'images/persons/ciprus/Kats.jpg',
        'm2_score_b': '1',
        'm2_score_w': '0',
        'm2_res_col': '&#9679;',
        'm2_res_score': 'Сдача',
        'm2_flag_b': Country.flag_belarus_m,
        'm2_flag_w': Country.flag_cyprus_m,
        'm3': 'results/matches/belarus-ciprus/3. Герасютин Никита(ч)-Sotiris Ioannides.sgf',
        'm3_w': 'results/matches/belarus-ciprus/g3.sgf',
        'm3_name_b': 'Герасютин Никита Эдуардович',
        'm3_name_w': 'Sotiris Ioannides',
        'm3_photo_b': 'images/persons/ger_nik.jpg',
        'm3_photo_w': 'images/persons/ciprus/Ioannides.jpg',
        'm3_score_b': '0',
        'm3_score_w': '1',
        'm3_res_col': '&#9675;',
        'm3_res_score': '55.5',
        'm3_flag_b': Country.flag_belarus_m,
        'm3_flag_w': Country.flag_cyprus_m,
        'm4': 'results/matches/belarus-ciprus/4. Phedias Christodoulides-Корбут Сергей(б).sgf',
        'm4_w': 'results/matches/belarus-ciprus/g4.sgf',
        'm4_name_b': 'Phedias Christodoulides',
        'm4_name_w': 'Корбут Сергей',
        'm4_photo_b': 'images/persons/ciprus/Christod.jpg',
        'm4_photo_w': 'images/persons/kor_se.jpg',
        'm4_score_b': '1',
        'm4_score_w': '0',
        'm4_res_col': '&#9679;',
        'm4_res_score': '8.5',
        'm4_flag_b': Country.flag_cyprus_m,
        'm4_flag_w': Country.flag_belarus_m,
    },
    {
        'date': '29.10.2019',
        'match_number': 'match-belarus-iceland-2019-10-29',
        'title': 'League D 2019/2020 2 тур',
        'flag1': 'images/flags-normal/by.png',
        'name1': 'Беларусь',
        'score1': '3',
        'player11': 'Супонев Александр Михайлович',
        'photo11': 'images/persons/sup_al.jpg',
        'score11': '1',
        'player12': 'Бусько Илья Владимирович',
        'photo12': 'images/persons/bus_il.jpg',
        'score12': '0',
        'player13': 'Герасютин Никита Эдуардович',
        'photo13': 'images/persons/ger_nik.jpg',
        'score13': '1',
        'player14': 'Корбут Сергей',
        'photo14': 'images/persons/kor_se.jpg',
        'score14': '1',
        'flag2': 'images/flags-normal/is.png',
        'name2': 'Исландия',
        'score2': '1',
        'player21': 'Hallbjorn Gudmundsson',
        'photo21': 'images/persons/no_photo.png',
        'score21': '0',
        'player22': 'Ólafur Sigurðarson',
        'photo22': 'images/persons/island/Sigur.jpg',
        'score22': '1',
        'player23': 'Þórbergur Ólafsson',
        'photo23': 'images/persons/no_photo.png',
        'score23': '0',
        'player24': 'Garpur Dagsson',
        'photo24': 'images/persons/island/dagsson.jpg',
        'score24': '0',
        'author': 'Герасютин Никита',
        'person_photo': 'images/persons/ger_nik.jpg',
        'news_ref': 'html/matches/2019_10_29_by_iceland.html',
        'address': 'pandanet-igs.com',
        'www_ref': 'https://pandanet-igs.com/communities/euroteamchamps/rounds/608#2',
        'ref_name': 'Беларусь - Исландия',
        'place_css': 'images/places/panda.jpg',
        'video_ref': 'results/matches/belarus-island/Belarus-Iceland.mp4',
        'video_author': 'Сурма Матеуш',
        'author_css': 'blue',
        'author_ref': './html/pages/players_lib.html',
        'm1': 'results/matches/belarus-island/1. Александр Михайлович(ч)-Hallbjorn Gudmundsson.sgf',
        'm1_w': 'results/matches/belarus-island/g1.sgf',
        'm1_name_b': 'Супонев Александр Михайлович',
        'm1_name_w': 'Hallbjorn Gudmundsson',
        'm1_photo_b': 'images/persons/sup_al.jpg',
        'm1_photo_w': 'images/persons/no_photo.png',
        'm1_score_b': '1',
        'm1_score_w': '0',
        'm1_flag_b': Country.flag_belarus_m,
        'm1_flag_w': Country.flag_iceland_m,
        'm1_res_col': '&#9679;',
        'm1_res_score': 'Сдача',
        'm2': 'results/matches/belarus-island/2. Ólafur Sigurðarson-Бусько Илья(б).sgf',
        'm2_w': 'results/matches/belarus-island/g2.sgf',
        'm2_name_b': 'Ólafur Sigurðarson',
        'm2_name_w': 'Бусько Илья Владимирович',
        'm2_photo_b': 'images/persons/island/Sigur.jpg',
        'm2_photo_w': 'images/persons/bus_il.jpg',
        'm2_score_b': '1',
        'm2_score_w': '0',
        'm2_res_col': '&#9679;',
        'm2_res_score': 'Сдача',
        'm2_flag_b': Country.flag_iceland_m,
        'm2_flag_w': Country.flag_belarus_m,
        'm3': 'results/matches/belarus-island/3. Герасютин Никита(ч)-Þórbergur Ólafsson.sgf',
        'm3_w': 'results/matches/belarus-island/g3.sgf',
        'm3_name_b': 'Герасютин Никита Эдуардович',
        'm3_name_w': 'Þórbergur Ólafsson',
        'm3_photo_b': 'images/persons/ger_nik.jpg',
        'm3_photo_w': 'images/persons/no_photo.png',
        'm3_score_b': '1',
        'm3_score_w': '0',
        'm3_res_col': '&#9679;',
        'm3_res_score': 'Сдача',
        'm3_flag_b': Country.flag_belarus_m,
        'm3_flag_w': Country.flag_iceland_m,
        'm4': 'results/matches/belarus-island/4. Garpur Dagsson-Корбут Сергей(б).sgf',
        'm4_w': 'results/matches/belarus-island/g4.sgf',
        'm4_name_b': 'Garpur Dagsson',
        'm4_name_w': 'Корбут Сергей Викторович',
        'm4_photo_b': 'images/persons/island/dagsson.jpg',
        'm4_photo_w': 'images/persons/kor_se.jpg',
        'm4_score_b': '0',
        'm4_score_w': '1',
        'm4_res_col': '&#9675;',
        'm4_res_score': '14.5',
        'm4_flag_b': Country.flag_iceland_m,
        'm4_flag_w': Country.flag_belarus_m,
    },
    {
        'date': '26.11.2019',
        'match_number': 'match-bulgaria-belarus-2019-11-26',
        'title': 'League D 2019/2020 3 тур',
        'flag1': 'images/flags-normal/bg.png',
        'name1': 'Болгария',
        'score1': '2',
        'player11': 'Sinan Djepov',
        'photo11': 'images/persons/bg_djepov.jpg',
        'score11': '1',
        'player12': 'Boyan Alexandrov',
        'photo12': 'images/persons/bg_alexandrov.jpg',
        'score12': '1',
        'player13': 'Alexander Yakimov',
        'photo13': 'images/persons/bg_yakimov.jpg',
        'score13': '0',
        'player14': 'Tsvetomir Varbanov',
        'photo14': 'images/persons/bg_varbanov.jpg',
        'score14': '0',
        'flag2': 'images/flags-normal/by.png',
        'name2': 'Беларусь',
        'score2': '2',
        'player21': 'Супонев Александр Михайлович',
        'photo21': 'images/persons/sup_al.jpg',
        'score21': '0',
        'player22': 'Бусько Илья Владимирович',
        'photo22': 'images/persons/bus_il.jpg',
        'score22': '0',
        'player23': 'Герасютин Никита Эдуардович',
        'photo23': 'images/persons/ger_nik.jpg',
        'score23': '1',
        'player24': 'Корбут Сергей Викторович',
        'photo24': 'images/persons/kor_se.jpg',
        'score24': '1',
        'author': 'Герасютин Никита',
        'person_photo': 'images/persons/ger_nik.jpg',
        'news_ref': 'html/matches/2019_11_26_by_bulgaria.html',
        'address': 'pandanet-igs.com',
        'www_ref': 'https://pandanet-igs.com/communities/euroteamchamps/rounds/609#3',
        'ref_name': 'Болгария - Беларусь',
        'place_css': 'images/places/panda.jpg',
        'video_ref': 'results/matches/bulgaria-belarus/Bulgaria-Belarus.mp4',
        'video_author': 'Динерштейн Александр Григорьевич',
        'author_css': 'pink',
        'author_ref': './html/pages/players_lib.html',
        'm1': 'results/matches/bulgaria-belarus/1.Sinan Djepov - Супонев Александр.sgf',
        'm1_w': 'results/matches/bulgaria-belarus/1.sgf',
        'm1_name_b': 'Sinan Djepov',
        'm1_name_w': 'Супонев Александр Михайлович',
        'm1_photo_b': 'images/persons/bg_djepov.jpg',
        'm1_photo_w': 'images/persons/sup_al.jpg',
        'm1_score_b': '1',
        'm1_score_w': '0',
        'm1_flag_b': Country.flag_bulgaria_m,
        'm1_flag_w': Country.flag_belarus_m,
        'm1_res_col': '&#9679;',
        'm1_res_score': 'Сдача',
        'm2': 'results/matches/bulgaria-belarus/2.Бусько Илья - Boyan Alexandrov.sgf',
        'm2_w': 'results/matches/bulgaria-belarus/2.sgf',
        'm2_name_b': 'Бусько Илья Владимирович',
        'm2_name_w': 'Boyan Alexandrov',
        'm2_photo_b': 'images/persons/bus_il.jpg',
        'm2_photo_w': 'images/persons/bg_alexandrov.jpg',
        'm2_score_b': '0',
        'm2_score_w': '1',
        'm2_res_col': '&#9675;',
        'm2_res_score': 'Сдача',
        'm2_flag_w': Country.flag_bulgaria_m,
        'm2_flag_b': Country.flag_belarus_m,
        'm3': 'results/matches/bulgaria-belarus/3.Alexander Yakimov - Герасютин Никита.sgf',
        'm3_w': 'results/matches/bulgaria-belarus/3.sgf',
        'm3_name_b': 'Alexander Yakimov',
        'm3_name_w': 'Герасютин Никита Эдуардович',
        'm3_photo_b': 'images/persons/bg_yakimov.jpg',
        'm3_photo_w': 'images/persons/ger_nik.jpg',
        'm3_score_b': '0',
        'm3_score_w': '1',
        'm3_res_col': '&#9675;',
        'm3_res_score': 'Сдача',
        'm3_flag_w': Country.flag_belarus_m,
        'm3_flag_b': Country.flag_bulgaria_m,
        'm4': 'results/matches/bulgaria-belarus/4.Корбут Сергей - Tsvetomir Varbanov.sgf',
        'm4_w': 'results/matches/bulgaria-belarus/4.sgf',
        'm4_name_b': 'Корбут Сергей Викторович',
        'm4_name_w': 'Tsvetomir Varbanov',
        'm4_photo_b': 'images/persons/kor_se.jpg',
        'm4_photo_w': 'images/persons/bg_varbanov.jpg',
        'm4_score_b': '1',
        'm4_score_w': '0',
        'm4_res_col': '&#9679;',
        'm4_res_score': '68.5',
        'm4_flag_b': Country.flag_belarus_m,
        'm4_flag_w': Country.flag_bulgaria_m,
    },
    {
        'date': '17.12.2019',
        'match_number': 'match-spain-belarus-2019-12-17',
        'title': 'League D 2019/2020 4 тур',
        'flag1': 'images/flags-normal/es.png',
        'name1': 'Испания',
        'score1': '4',
        'player11': 'Juan Francisco Garcia de la Banda',
        'photo11': 'images/persons/no_photo.png',
        'score11': '1',
        'player12': 'Miguel Angel Antolinez',
        'photo12': 'images/persons/no_photo.png',
        'score12': '1',
        'player13': 'Juan Carlos del Rio',
        'photo13': 'images/persons/no_photo.png',
        'score13': '1',
        'player14': 'Jose Manuel Pavon',
        'photo14': 'images/persons/no_photo.png',
        'score14': '1',
        'flag2': 'images/flags-normal/by.png',
        'name2': 'Беларусь',
        'score2': '0',
        'player21': 'Супонев Александр Михайлович',
        'photo21': 'images/persons/sup_al.jpg',
        'score21': '0',
        'player22': 'Герасютин Никита Эдуардович',
        'photo22': 'images/persons/ger_nik.jpg',
        'score22': '0',
        'player23': 'Корбут Сергей Викторович',
        'photo23': 'images/persons/kor_se.jpg',
        'score23': '0',
        'player24': 'Чайко Виктор',
        'photo24': 'images/persons/chaiko.jpg',
        'score24': '0',
        'author': 'Герасютин Никита',
        'person_photo': 'images/persons/ger_nik.jpg',
        'news_ref': 'html/matches/2019_12_17_by_spain.html',
        'address': 'pandanet-igs.com',
        'www_ref': 'https://pandanet-igs.com/communities/euroteamchamps/rounds/610#4',
        'ref_name': 'Испания - Беларусь',
        'place_css': 'images/places/panda.jpg',
        'video_ref': '',//'results/matches/spain-belarus/Spain-Belarus.mp4',
        'video_author': '',//'Динерштейн Александр Григорьевич',
        'author_css': '',//'pink',
        'author_ref': './html/pages/players_lib.html',
        'm1': 'results/matches/spain-belarus/1_Juan_Francisco_Garcia_de_la_Banda_-_Suponev_Alexandr.sgf',
        'm1_w': 'results/matches/spain-belarus/1.sgf',
        'm1_name_b': 'Juan Francisco Garcia de la Banda',
        'm1_name_w': 'Супонев Александр Михайлович',
        'm1_photo_b': 'images/persons/no_photo.png',
        'm1_photo_w': 'images/persons/sup_al.jpg',
        'm1_score_b': '1',
        'm1_score_w': '0',
        'm1_flag_b': Country.flag_spain_m,
        'm1_flag_w': Country.flag_belarus_m,
        'm1_res_col': '&#9679;',
        'm1_res_score': 'Сдача',
        'm2': 'results/matches/spain-belarus/2_Gerasyutin_Nikita_-_Miguel_Angel_Antolinez.sgf',
        'm2_w': 'results/matches/spain-belarus/2.sgf',
        'm2_name_b': 'Герасютин Никита Эдуардович',
        'm2_name_w': 'Miguel Angel Antolinez',
        'm2_photo_b': 'images/persons/ger_nik.jpg',
        'm2_photo_w': 'images/persons/no_photo.png',
        'm2_score_b': '0',
        'm2_score_w': '1',
        'm2_res_col': '&#9675;',
        'm2_res_score': '9.5',
        'm2_flag_w': Country.flag_spain_m,
        'm2_flag_b': Country.flag_belarus_m,
        'm3': 'results/matches/spain-belarus/3_Juan_Carlos_del_Rio_-_Korbut_Sergey.sgf',
        'm3_w': 'results/matches/spain-belarus/3.sgf',
        'm3_name_b': 'Juan Carlos del Rio',
        'm3_name_w': 'Корбут Сергей Викторович',
        'm3_photo_b': 'images/persons/no_photo.png',
        'm3_photo_w': 'images/persons/ger_nik.jpg',
        'm3_score_b': '1',
        'm3_score_w': '0',
        'm3_res_col': '&#9679;',
        'm3_res_score': 'Сдача',
        'm3_flag_w': Country.flag_belarus_m,
        'm3_flag_b': Country.flag_spain_m,
        'm4': 'results/matches/spain-belarus/4_Chayko_Viktor_-_Jose_Manuel_Pavon_n.sgf',
        'm4_w': 'results/matches/spain-belarus/4.sgf',
        'm4_name_b': 'Чайко Виктор',
        'm4_name_w': 'Jose Manuel Pavon',
        'm4_photo_b': 'images/persons/chaiko.jpg',
        'm4_photo_w': 'images/persons/no_photo.png',
        'm4_score_b': '0',
        'm4_score_w': '1',
        'm4_res_col': '&#9675;',
        'm4_res_score': '6.5',
        'm4_flag_b': Country.flag_belarus_m,
        'm4_flag_w': Country.flag_spain_m,
    },
];